#!/bin/bash

PCK='minetest 0ad wesnoth sauerbraten neverball supertuxkart'

# ===============================================================

apt-get update
echo
echo "Start installing: $PCK"
apt-get install --assume-yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold --force-yes $PCK
echo "Done"
