#!/bin/bash

PCK='steam minetest 0ad wesnoth sauerbraten neverball supertuxkart'

if [ "$(uname -m)" == "x86_64" ]; then
  PCK="$PCK libgl1-mesa-glx:i386"
fi

# ===============================================================

# --force-yes is deprecated in stretch
FORCE='--force-yes'
VER=$(head -c 1 /etc/debian_version | sed 's/[a-zA-Z]/0/' 2>/dev/null || echo 0)
if [ "$VER" -eq 0 ] || [ "$VER" -gt 8 ]; then
  FORCE='--allow-downgrades --allow-remove-essential --allow-change-held-packages'
fi

# Preseeding doesn't seem to work with steam:
# http://lists.alioth.debian.org/pipermail/pkg-games-devel/2014-December/033140.html
#echo "Preseeding for steam..."
#echo "steam steam/question select \"I AGREE\"" | debconf-set-selections
#echo "steam steam/license note " | debconf-set-selections
#echo "steam steam/purge note " | debconf-set-selections


apt-get update
echo
echo "Start installing: $PCK"
export DEBIAN_FRONTEND=gnome
apt-get install --assume-yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold $FORCE $PCK
echo "Done"
