#!/bin/bash

XFCE='gimp inkscape shotwell clementine handbrake soundconverter pitivi transmission-gtk'
KDE='gimp inkscape digikam amarok handbrake soundconverter kdenlive ktorrent'

# =============================================

PCK=$XFCE
if [ "$(pidof kdeinit4)" ]; then
  PCK=$KDE
fi

apt-get update
echo
echo echo "Start installing: $PCK"
export DEBIAN_FRONTEND=gnome
apt-get install --assume-yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold --force-yes $PCK
echo "Done"