#!/bin/bash

XFCE='gimp inkscape shotwell clementine handbrake soundconverter pitivi transmission-gtk'
KDE='gimp inkscape digikam amarok handbrake soundconverter kdenlive ktorrent'

# =============================================

# --force-yes is deprecated in stretch
FORCE='--force-yes'
VER=$(head -c 1 /etc/debian_version | sed 's/[a-zA-Z]/0/' 2>/dev/null || echo 0)
if [ "$VER" -eq 0 ] || [ "$VER" -gt 8 ]; then
  FORCE='--allow-downgrades --allow-remove-essential --allow-change-held-packages'
fi

PCK=$KDE
if [ "$(pidof xfce4-session)" ]; then
  PCK=$XFCE
fi

apt-get update
echo
echo echo "Start installing: $PCK"
export DEBIAN_FRONTEND=gnome
apt-get install --assume-yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold $FORCE $PCK
echo "Done"