#!/bin/bash

AMD64='libdvdcss2 w64codecs solydxk-flashplugin-11'
I386='libdvdcss2 w32codecs solydxk-flashplugin-11'

# ======================================

PCK=$I386
if [ "$(uname -m)" == "x86_64" ]; then
  PCK=$AMD64
fi

apt-get update
echo
echo "Start installing: $PCK"
export DEBIAN_FRONTEND=gnome
apt-get install --assume-yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold --force-yes $PCK
echo "Done"
