#!/bin/bash

AMD64='libdvdcss2 w64codecs solydxk-flashplugin-11'
I386='libdvdcss2 w32codecs solydxk-flashplugin-11'

# ======================================

# --force-yes is deprecated in stretch
FORCE='--force-yes'
VER=$(head -c 1 /etc/debian_version | sed 's/[a-zA-Z]/0/' 2>/dev/null || echo 0)
if [ "$VER" -eq 0 ] || [ "$VER" -gt 8 ]; then
  FORCE='--allow-downgrades --allow-remove-essential --allow-change-held-packages'
fi

PCK=$I386
if [ "$(uname -m)" == "x86_64" ]; then
  PCK=$AMD64
fi

apt-get update
echo
echo "Start installing: $PCK"
export DEBIAN_FRONTEND=gnome
apt-get install --assume-yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold $FORCE $PCK
echo "Done"
