#!/bin/bash

AMD64='playonlinux wine32 libasound2-plugins:i386 libgl1-mesa-glx:i386 libxft2:i386 libcups2:i386'
I386='playonlinux wine32 libasound2-plugins libgl1-mesa-glx libxft2 libcups2'

PCK=$I386
if [ "$(uname -m)" == "x86_64" ]; then
  PCK=$AMD64
fi

# ===============================================================

# --force-yes is deprecated in stretch
FORCE='--force-yes'
VER=$(head -c 1 /etc/debian_version | sed 's/[a-zA-Z]/0/' 2>/dev/null || echo 0)
if [ "$VER" -eq 0 ] || [ "$VER" -gt 8 ]; then
  FORCE='--allow-downgrades --allow-remove-essential --allow-change-held-packages'
fi

apt-get update
echo
echo "Start installing: $PCK"
export DEBIAN_FRONTEND=gnome
apt-get install --assume-yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold --no-install-recommends $FORCE $PCK
echo "Done"
